review: earthfile and gha rework

diff --git a/examples/Earthfile b/examples/Earthfile
--- a/examples/Earthfile
+++ b/examples/Earthfile
@@ -1,15 +1,19 @@
 VERSION --try 0.8
 
-# TODO use once internal actions set up on this repo
 ARG --global EXOSCALE_DOCKER_REGISTRY=registry.internal.exoscale.ch
 ARG --global GO_VERSION=1.26.5
 
-# Base image with source code
-source:
-    FROM library/golang:${GO_VERSION}-alpine
-
+# --- Base images ---
+deps:
+    FROM ${EXOSCALE_DOCKER_REGISTRY}/docker.io/library/golang:${GO_VERSION}-alpine
     WORKDIR /build
     COPY go.mod go.sum ./
+    RUN go mod download
+    RUN go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest
+    RUN go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest
+
+source:
+    FROM +deps
     COPY . .
 
 # --- Codegen ---
@@ -17,7 +21,6 @@ source:
 # Generates code from OpenAPI specs and updates local files
 gen-oapi:
     FROM +source
-    RUN go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest
     RUN oapi-codegen -config api/public/cfg.yaml api/public/api.yaml
 	RUN oapi-codegen -config api/internal/cfg.yaml api/internal/api.yaml
     SAVE ARTIFACT api/public/api.gen.go AS LOCAL api/public/api.gen.go
@@ -25,7 +28,7 @@ gen-oapi:
 
 # Generates code from protobuf spec and updates local files
 gen-proto:
-    FROM bufbuild/buf:1
+    FROM ${EXOSCALE_DOCKER_REGISTRY}/docker.io/bufbuild/buf:1
     WORKDIR /app
     COPY proto proto
 	RUN buf generate proto --template proto/buf.gen.yaml -o proto
@@ -34,14 +37,23 @@ gen-proto:
 
 # --- Quality ---
 
+# Formatting check that simply fails if not formatted correctly
 format:
     FROM +source
-    RUN test -z "$(gofmt -l . | grep -v '^vendor/')" || (gofmt -l . | grep -v '^vendor/' && exit 1)
+    RUN unformatted="$(gofmt -l . | grep -v '^vendor/')"; test -z "$unformatted" || (echo "$unformatted" && exit 1)
 
+# Lint check that will simply fail if linting fails
 lint:
     FROM +source
-    RUN go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.11.4
     RUN golangci-lint run ./...
+
+# Formatting and lint fixes, applied to the local filesystem
+format-lint-fix:
+    FROM +source
+    RUN golangci-lint fmt ./...
+    RUN golangci-lint run --fix ./...
+    RUN rm -rf ./.tmp-* # Remove temporary dirs
+    SAVE ARTIFACT ./* AS LOCAL .
 
 vulncheck:
     FROM +source
@@ -49,7 +61,7 @@ vulncheck:
     RUN govulncheck ./...
 
 buf-lint:
-    FROM bufbuild/buf:1
+    FROM ${EXOSCALE_DOCKER_REGISTRY}/docker.io/bufbuild/buf:1
     WORKDIR /app
     COPY proto proto
 	RUN buf lint proto
@@ -69,25 +81,29 @@ build:
     SAVE ARTIFACT /app/${NAME}
 
 deploy:
-    FROM alpine
+    FROM ${EXOSCALE_DOCKER_REGISTRY}/docker.io/library/alpine:3.24
     ARG --required NAME
-    ARG TAG=dev
+    ARG --required TAGS
     COPY (+build/${NAME} --NAME=${NAME}) /app/${NAME}
 
     USER 65534
     CMD ["/app/${NAME}"]
 
-    # Commented out until we set up internal actions on this repo
-    # SAVE IMAGE --push ${EXOSCALE_DOCKER_REGISTRY}/exoscale/stelling/${NAME}:${TAG}
+    FOR TAG IN $TAGS
+        SAVE IMAGE --push ${EXOSCALE_DOCKER_REGISTRY}/exoscale/stelling/${NAME}:${TAG}
+    END
 
-grpc-server:
-    ARG TAG=dev
-    FROM +deploy --NAME=grpc-server --TAG=${TAG}
+# --- CI pipeline ---
 
-http-server:
-    ARG TAG=dev
-    FROM +deploy --NAME=http-server --TAG=${TAG}
-
-job:
-    ARG TAG=dev
-    FROM +deploy --NAME=job --TAG=${TAG}
+# Full CI pipeline which runs checks, then builds images.
+pipeline-ci:
+    ARG TAGS=dev
+    WAIT
+        BUILD +format
+        BUILD +lint
+        BUILD +test
+        BUILD +buf-lint
+    END
+    BUILD +deploy --NAME=grpc-server --TAGS=${TAGS}
+    BUILD +deploy --NAME=http-server --TAGS=${TAGS}
+    BUILD +deploy --NAME=job --TAGS=${TAGS}
